### ISSUE TITLE
Exception: "setVisible is not a function"

### ISSUE THREAD

**Issue by jdawsongit** [mark-hahn/box-select#4]
Using Atom 1.19.1 x64 on Mac OS X 10.12.6, I installed box-edit 0.1.3, and hit Alt-S in a file. A red selection rectangle appeared, along with an error window with the exception below:

```
TypeError: this.editor.getLastCursor(...).setVisible is not a function
    at BoxEdit.atomSelectionsToBox (/Users/jdawson/.atom/packages/box-edit/lib/box.coffee:43:29)
    at BoxEdit.toggle (/Users/jdawson/.atom/packages/box-edit/lib/box-edit.coffee:32:6)
    at HTMLElement.subs.add.atom.commands.add.box-edit:toggle (/Users/jdawson/.atom/packages/box-edit/lib/box-edit.coffee:15:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

At this point, the plugin appears broken. I can't make the red rectangle go away, even if I switch to other tabs, settings, etc., or hit Escape. My only recourse appears to be to restart Atom.

**Comment by MartinBonner** [comment]
I suggest closing this one as a duplicate of #5 (do it that way round because #5 is what Atom points to when you hit the problem as it says "this issuer has already been reported")

**Comment by jdawsongit** [comment]
Closing.

**Comment by mark-hahn** [comment]
I cannot believe anyone would still use atom.  Vscode is infinitely better.
