### ISSUE TITLE
Uncaught TypeError: this.editor.getLastCursor(...).setVisible is not a function

### ISSUE THREAD

**Issue by varsitynetworks** [mark-hahn/box-select#5]
[Enter steps to reproduce:]

1. Just hit "alt-s"

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.2
**Thrown From**: [box-edit](https://github.com/mark-hahn/box-edit) package 0.1.3

### Stack Trace

Uncaught TypeError: this.editor.getLastCursor(...).setVisible is not a function

```
At /Users/avi/.atom/packages/box-edit/lib/box.coffee:43

TypeError: this.editor.getLastCursor(...).setVisible is not a function
    at BoxEdit.atomSelectionsToBox (/packages/box-edit/lib/box.coffee:43:29)
    at BoxEdit.toggle (/packages/box-edit/lib/box-edit.coffee:32:6)
    at /packages/box-edit/lib/box-edit.coffee:15:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:08.8.0 box-edit:toggle (input.hidden-input)
```

### Non-Core Packages

```
box-edit 0.1.3 
git-plus 7.9.3 
php-debug 0.2.5 
```

**Comment by TommieEdwardBerry** [comment]
I see the same issue
![boxissue](https://user-images.githubusercontent.com/24882862/30547784-e87e20b6-9c55-11e7-9fca-8d271d9e9266.png)

**Comment by gliviu** [comment]
box-edit no longer works probably due to this issue. I can draw the box but no manipulation possible.

**Comment by alan-cugler** [comment]
Still doesnt work for me in 2020

**Comment by mark-hahn** [comment]
I dropped support of my atom plugins several years ago.  Unless someone
else forks and supports this it will remain broken.

P.S.  Have you tried vscode?
